{% set version = "1.4.2" %}

package:
  name: go
  version: {{ version }}

source:
  fn: go-{{ version }}.tar.gz
  url: https://storage.googleapis.com/golang/go{{ version }}.src.tar.gz
  sha1: 460caac03379f746c473814a65223397e9c9a2f6

build:
  number: 0
  skip: true  # [win]
  binary_relocation: false

requirements:
  build:
    - pkg-config
    - pcre

test:
  files:
    - hello.go

  commands:
    - GOROOT="${PREFIX}/go" go help
    - GOROOT="${PREFIX}/go" go run hello.go

about:
  home: http://golang.org
  license: BSD 3-Clause
  summary: Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.

extra:
  recipe-maintainers:
    - jakirkham
